### PR TITLE
update startup timeout to 10 min

### PR DESCRIPTION
**Pull request by bolliger32**
instead of 15 min

### CODE REVIEW

**Review by delgadom — APPROVED** [review]

**Comment by delgadom** [comment]
thanks! 👍

**Review by brews — APPROVED** [review]
Looks good to me!

**Comment by brews** [comment]
Might want to put a brief writeup (or sentence) on why this change is needed? It's because user jupyterhub pods have a legit long timeout with the coastal images?

**Comment by bolliger32** [comment]
@brews No I don't think its something that's coastal specific. We're tightening up the timeout time. It was originally 5 min and that was too short sometimes b/c our images are big. So then we went to 15 min. But @delgadom pointed out that we might be able to get it a little shorter and that would make it quicker to diagnose when there actually is an issue, rather than having to wait 15 min.

Were you thinking document the reason for the change in the code? Or is this comment in the PR what you were looking for

**Comment by brews** [comment]
Ah! Awesome, thanks much @bolliger32. I'm only now catching up with my slack messages.

Could go either way on where to document it. For something little like this I think it's fine to write our thinking in this PR as it gives us a way to audit the change and understand our thinking if something goes wrong in the near future.

If it is a reaaally critical and sensitive number that some knuckhead might changes and unintentionally break everything -- then I'd say go for an inline comment with big violent letters and threats of an ancient curse.

Does that sound reasonable?

**Comment by bolliger32** [comment]
Yeah for sure just added a quick note to guide future knuckleheads

**Pull request merged**
